#!/bin/bash -login
 
### define resources needed:
### walltime - how long you expect the job to run
#PBS -l walltime=04:00:00
 
### nodes:ppn - how many nodes & cores per node (ppn) that you require
#PBS -l nodes=1:ppn=8
 
### mem: amount of memory that the job will need
#PBS -l mem=550gb
 
### you can give your job a name for easier identification
#PBS -N refsoil_plasmid
 
### change to the working directory where your code is located
cd /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/plasmids

##PLASMID GENBANK
#pull from ncbi
python /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/ref_soil/script_download_refsoil/fetch_genbank.py /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/plasmids/refsoil_plasmids.txt refsoil_plasmid_genbank


##PLASMID PROTEIN
#pull from ncbi
python /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/ref_soil/script_download_refsoil/fetch_fasta_protein.py /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/plasmids/refsoil_plasmids.txt refsoil_plasmid_protein_fasta

#concatenate files
cat refsoil_plasmid_protein_fasta/* > refsoil_plasmid_protein.fasta

#tidy names
awk '/^>/{print $1;next}{print}' refsoil_plasmid_protein.fasta > cleaned_refsoil_plasmid_protein.fasta
sed -i 's/lcl|//g' cleaned_refsoil_plasmid_protein.fasta
sed -i 's/_prot_/ from /g' cleaned_refsoil_plasmid_protein.fasta
sed -i 's/>/> /g' cleaned_refsoil_plasmid_protein.fasta
awk '/^>/{print ">" $4 " from " $2;next}{print}' cleaned_refsoil_plasmid_protein.fasta > plasmid.protein.fa

#linearize fasta
awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);}  END {printf("\n");}' < plasmid.protein.long.fa > plasmid.protein.fa

##PLASMID CDS
#pull from ncbi
python /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/ref_soil/script_download_refsoil/fetch_fasta_cds.py /mnt/research/ShadeLab/Dunivin/hmmsearch/refsoil_tree/plasmids/refsoil_plasmids.txt refsoil_plasmid_cds_fasta

#concatenate files
cat refsoil_plasmid_cds_fasta/*.fa > refsoil_plasmid_cds.fasta

#tidy names
awk '/^>/{print $1;next}{print}' refsoil_plasmid_cds.fasta > cleaned_refsoil_plasmid_cds.fasta
sed -i 's/lcl|//g' cleaned_refsoil_plasmid_cds.fasta
sed -i 's/_prot_/ from /g' cleaned_refsoil_plasmid_cds.fasta
sed -i 's/>/> /g' cleaned_refsoil_plasmid_cds.fasta
awk '/^>/{print ">" $4 " from " $2;next}{print}' cleaned_refsoil_plasmid_cds.fasta > plasmid.cds.long.fa

#linearize fasta
awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);}  END {printf("\n");}' < plasmid.cds.long.fa > plasmid.cds.fa